{% set version = "1.0.0" %}

package:
  name: obi
  version: {{ version }}
about:
  home: https://github.com/jcalvento/obi
  license: GPL-3.0
  summary: 'Positive selection analyser'
  description: |
    This package receives a protein chain and scans it for positive selection events. To install run conda install -c jcalvento obi --channel bioconda
  doc_source_url: https://github.com/jcalvento/obi/blob/master/README.md
source:
  path: ..
requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - biopython =1.74
    - blas =1.0
    - cd-hit =4.8.1
    - clustalo =1.2.3
    - coverage =5.3
    - hyphy =2.5.8
    - iqtree =2.0.3
    - pytest =5.2.4
    - requests =2.23.0
    - blast =2.10.1
    - marshmallow =3.9.1